## Scryfall - Data Cleaning and Manipulation

Using unique artwork dataset downloaded from: https://scryfall.com/docs/api/bulk-data

In [1]:
import pandas as pd

In [2]:
df = pd.read_json('./data/scryfall/unique-artwork-20260108221918.json.zip', compression='zip')
df.head()

,object,id,oracle_id,multiverse_ids,mtgo_id,arena_id,tcgplayer_id,cardmarket_id,name,lang,...,flavor_name,attraction_lights,color_indicator,printed_name,life_modifier,hand_modifier,content_warning,printed_type_line,printed_text,variation_of
0,card,0000419b-0bba-4488-8f7a-6194544ce91e,b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6,[668564],129825.0,91829.0,558404.0,777725.0,Forest,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,card,0000579f-7b35-4ed3-b44c-db2a538066fe,44623693-51d6-49ad-8cd7-140505caf02f,[109722],25527.0,NaN,14240.0,13850.0,Fury Sliver,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,card,00006596-1166-4a79-8443-ca9f82e6db4e,8ae3562f-28b7-4462-96ed-be0cf7052ccc,[189637],34586.0,NaN,33347.0,21851.0,Kor Outfitter,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,card,0000cd57-91fe-411f-b798-646e965eec37,9f0d82ae-38bf-45d8-8cda-982b6ead1d72,[435231],65170.0,66119.0,145764.0,301766.0,Siren Lookout,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,card,0001e77a-7fff-49d2-a55c-42f6fdf6db08,396b088d-f9af-4ee1-843f-dbe1633f9cc8,[629564],116428.0,86752.0,513888.0,730003.0,Obyra's Attendants // Desperate Parry,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print("Number of rows: ", len(df))
print("Column names:" , df.columns)

Number of rows:  50513
Column names: Index(['object', 'id', 'oracle_id', 'multiverse_ids', 'mtgo_id', 'arena_id',
       'tcgplayer_id', 'cardmarket_id', 'name', 'lang', 'released_at', 'uri',
       'scryfall_uri', 'layout', 'highres_image', 'image_status', 'image_uris',
       'mana_cost', 'cmc', 'type_line', 'oracle_text', 'colors',
       'color_identity', 'keywords', 'produced_mana', 'legalities', 'games',
       'reserved', 'game_changer', 'foil', 'nonfoil', 'finishes', 'oversized',
       'promo', 'reprint', 'variation', 'set_id', 'set', 'set_name',
       'set_type', 'set_uri', 'set_search_uri', 'scryfall_set_uri',
       'rulings_uri', 'prints_search_uri', 'collector_number', 'digital',
       'rarity', 'card_back_id', 'artist', 'artist_ids', 'illustration_id',
       'border_color', 'frame', 'full_art', 'textless', 'booster',
       'story_spotlight', 'prices', 'related_uris', 'purchase_uris',
       'mtgo_foil_id', 'power', 'toughness', 'flavor_text', 'edhrec_rank',
       'penny_rank', 'card_faces', 'all_parts', 'preview', 'security_stamp',
       'promo_types', 'watermark', 'frame_effects', 'loyalty', 'resource_id',
       'tcgplayer_etched_id', 'flavor_name', 'attraction_lights',
       'color_indicator', 'printed_name', 'life_modifier', 'hand_modifier',
       'content_warning', 'printed_type_line', 'printed_text', 'variation_of'],
      dtype='object')

In [4]:
# keep only needed columns
filtered_df = df[['id',
                'oracle_id',
                'name',
                'set_id',
                'set',
                'set_name',
                'artist_ids',
                'artist',
                'released_at',
                'type_line', # in  the format '[type] — [subtype]' (e.g. Creature — Kor Soldier)
                'keywords',
                'rarity',
                'color_identity',
                'cmc', # card's mana value
                'power',
                'toughness',
                'edhrec_rank',
                'legalities',
                'prices',
                'image_uris',
                'card_faces', # indicates whether card is multi-face
            ]]
filtered_df.head()

,id,oracle_id,name,set_id,set,set_name,artist_ids,artist,released_at,type_line,...,rarity,color_identity,cmc,power,toughness,edhrec_rank,legalities,prices,image_uris,card_faces
0,0000419b-0bba-4488-8f7a-6194544ce91e,b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6,Forest,a2f58272-bba6-439d-871e-7a46686ac018,blb,Bloomburrow,[22ab27e3-6476-48f1-a9f7-9a9e86339030],David Robert Hovey,2024-08-02,Basic Land — Forest,...,common,[G],0.0,NaN,NaN,NaN,"{'standard': 'legal', 'future': 'legal', 'hist...","{'usd': '0.25', 'usd_foil': '0.77', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,NaN
1,0000579f-7b35-4ed3-b44c-db2a538066fe,44623693-51d6-49ad-8cd7-140505caf02f,Fury Sliver,c1d109bc-ffd8-428f-8d7d-3f8d7e648046,tsp,Time Spiral,[d48dd097-720d-476a-8722-6a02854ae28b],Paolo Parente,2006-10-06,Creature — Sliver,...,uncommon,[R],6.0,3,3,9808.0,"{'standard': 'not_legal', 'future': 'not_legal...","{'usd': '0.46', 'usd_foil': '3.79', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,NaN
2,00006596-1166-4a79-8443-ca9f82e6db4e,8ae3562f-28b7-4462-96ed-be0cf7052ccc,Kor Outfitter,eb16a2bd-a218-4e4e-8339-4aa1afc0c8d2,zen,Zendikar,[aa7e89ed-d294-4633-9057-ce04dacfcfa4],Kieran Yanner,2009-10-02,Creature — Kor Soldier,...,common,[W],2.0,2,2,19672.0,"{'standard': 'not_legal', 'future': 'not_legal...","{'usd': '0.11', 'usd_foil': '1.77', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,NaN
3,0000cd57-91fe-411f-b798-646e965eec37,9f0d82ae-38bf-45d8-8cda-982b6ead1d72,Siren Lookout,fe0dad85-54bc-4151-9200-d68da84dd0f2,xln,Ixalan,[a8e7b854-b15a-421a-b66d-6e68187ae285],Chris Rallis,2017-09-29,Creature — Siren Pirate,...,common,[U],3.0,1,2,18843.0,"{'standard': 'not_legal', 'future': 'not_legal...","{'usd': '0.04', 'usd_foil': '0.21', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,NaN
4,0001e77a-7fff-49d2-a55c-42f6fdf6db08,396b088d-f9af-4ee1-843f-dbe1633f9cc8,Obyra's Attendants // Desperate Parry,79139661-13ee-43c4-8bad-a8c069f1a1df,woe,Wilds of Eldraine,[e2f13a9a-57c5-40de-81d4-3b0723899cdf],Andreas Zafiratos,2023-09-08,Creature — Faerie Wizard // Instant — Adventure,...,common,[U],5.0,3,4,17568.0,"{'standard': 'legal', 'future': 'legal', 'hist...","{'usd': '0.08', 'usd_foil': '0.13', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,"[{'object': 'card_face', 'name': 'Obyra's Atte..."

In [5]:
# check for missing values
print("Count of null values in each column: ")
filtered_df.isnull().sum()

Count of null values in each column:

id                    0
oracle_id            71
name                  0
set_id                0
set                   0
set_name              0
artist_ids            2
artist                0
released_at           0
type_line            71
keywords              0
rarity                0
color_identity        0
cmc                  71
power             26700
toughness         26700
edhrec_rank        8145
legalities            0
prices                0
image_uris         3053
card_faces        47047
dtype: int64

### Exclude multiface cards

Some magic cards are multi-faced, with faces divided on the front of the card like [split cards](https://scryfall.com/search?q=is%3Asplit) and [flip cards](https://scryfall.com/search?q=is%3Aflip), or double-sided like [transform cards](https://scryfall.com/search?q=is%3Atransform). These cards can have multiple artwork and/or ability (power/toughness). Scryfall indicates whether a card is multi-faced using the `card_faces` attribute, an array of card face objects with individual properties of name, type_line, power, toughness, image_uris, etc for each face. For single-faced cards, `card_faces` will be NaN. Based on the null values above, around 3.5k out of 50k cards from this dataset are multiface.

For our project, we will **exclude** multiface cards and only focus on cards with a single artwork/ability. We can expand to cover multiface cards later on.

In [6]:
# keep only rows where card_faces IS null (these are single-faced cards)
cleaned_df = filtered_df[filtered_df['card_faces'].isnull()].copy()
cleaned_df.drop(columns=['card_faces'], inplace=True)

### Extract type & subtype from type_line

In [7]:
# type_line is in the format '[type] — [subtype]' (e.g. Creature — Kor Soldier)
# note: not all cards have a subtype
cleaned_df['type'] = cleaned_df['type_line'].str.split('—').str[0].str.strip()
cleaned_df['subtype'] = cleaned_df['type_line'].str.split('—').str[1].str.strip()
cleaned_df.head()

,id,oracle_id,name,set_id,set,set_name,artist_ids,artist,released_at,type_line,...,color_identity,cmc,power,toughness,edhrec_rank,legalities,prices,image_uris,type,subtype
0,0000419b-0bba-4488-8f7a-6194544ce91e,b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6,Forest,a2f58272-bba6-439d-871e-7a46686ac018,blb,Bloomburrow,[22ab27e3-6476-48f1-a9f7-9a9e86339030],David Robert Hovey,2024-08-02,Basic Land — Forest,...,[G],0.0,NaN,NaN,NaN,"{'standard': 'legal', 'future': 'legal', 'hist...","{'usd': '0.25', 'usd_foil': '0.77', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,Basic Land,Forest
1,0000579f-7b35-4ed3-b44c-db2a538066fe,44623693-51d6-49ad-8cd7-140505caf02f,Fury Sliver,c1d109bc-ffd8-428f-8d7d-3f8d7e648046,tsp,Time Spiral,[d48dd097-720d-476a-8722-6a02854ae28b],Paolo Parente,2006-10-06,Creature — Sliver,...,[R],6.0,3,3,9808.0,"{'standard': 'not_legal', 'future': 'not_legal...","{'usd': '0.46', 'usd_foil': '3.79', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,Creature,Sliver
2,00006596-1166-4a79-8443-ca9f82e6db4e,8ae3562f-28b7-4462-96ed-be0cf7052ccc,Kor Outfitter,eb16a2bd-a218-4e4e-8339-4aa1afc0c8d2,zen,Zendikar,[aa7e89ed-d294-4633-9057-ce04dacfcfa4],Kieran Yanner,2009-10-02,Creature — Kor Soldier,...,[W],2.0,2,2,19672.0,"{'standard': 'not_legal', 'future': 'not_legal...","{'usd': '0.11', 'usd_foil': '1.77', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,Creature,Kor Soldier
3,0000cd57-91fe-411f-b798-646e965eec37,9f0d82ae-38bf-45d8-8cda-982b6ead1d72,Siren Lookout,fe0dad85-54bc-4151-9200-d68da84dd0f2,xln,Ixalan,[a8e7b854-b15a-421a-b66d-6e68187ae285],Chris Rallis,2017-09-29,Creature — Siren Pirate,...,[U],3.0,1,2,18843.0,"{'standard': 'not_legal', 'future': 'not_legal...","{'usd': '0.04', 'usd_foil': '0.21', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,Creature,Siren Pirate
5,0001f1ef-b957-4a55-b47f-14839cdbab6f,ef027846-be81-4959-a6b5-56bd01b1e68a,Venerable Knight,a90a7b2f-9dd8-4fc7-9f7d-8ea2797ec782,eld,Throne of Eldraine,[9c201dbe-db56-429a-87e6-189ea70c2632],Colin Boyer,2019-10-04,Creature — Human Knight,...,[W],1.0,2,1,18404.0,"{'standard': 'not_legal', 'future': 'not_legal...","{'usd': '0.15', 'usd_foil': '0.34', 'usd_etche...",{'small': 'https://cards.scryfall.io/small/fro...,Creature,Human Knight

### Extract legality, price (USD), and images from dictionary format

In [8]:
# check formatting of legalities, prices, and image_uris dict
print(cleaned_df['legalities'][0])
print(cleaned_df['prices'][0])
print(cleaned_df['image_uris'][0])

{'standard': 'legal', 'future': 'legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pioneer': 'legal', 'modern': 'legal', 'legacy': 'legal', 'pauper': 'legal', 'vintage': 'legal', 'penny': 'legal', 'commander': 'legal', 'oathbreaker': 'legal', 'standardbrawl': 'legal', 'brawl': 'legal', 'alchemy': 'legal', 'paupercommander': 'legal', 'duel': 'legal', 'oldschool': 'not_legal', 'premodern': 'legal', 'predh': 'legal'}
{'usd': '0.25', 'usd_foil': '0.77', 'usd_etched': None, 'eur': '0.23', 'eur_foil': '0.58', 'tix': '0.03'}
{'small': 'https://cards.scryfall.io/small/front/0/0/0000419b-0bba-4488-8f7a-6194544ce91e.jpg?1721427487', 'normal': 'https://cards.scryfall.io/normal/front/0/0/0000419b-0bba-4488-8f7a-6194544ce91e.jpg?1721427487', 'large': 'https://cards.scryfall.io/large/front/0/0/0000419b-0bba-4488-8f7a-6194544ce91e.jpg?1721427487', 'png': 'https://cards.scryfall.io/png/front/0/0/0000419b-0bba-4488-8f7a-6194544ce91e.png?1721427487', 'art_crop': 'https://cards.scryfall.io/art_crop/front/0/0/0000419b-0bba-4488-8f7a-6194544ce91e.jpg?1721427487', 'border_crop': 'https://cards.scryfall.io/border_crop/front/0/0/0000419b-0bba-4488-8f7a-6194544ce91e.jpg?1721427487'}

In [9]:
# use 'commander' and 'standard' play formats for now
cleaned_df['legality_commander'] = cleaned_df['legalities'].str.get('commander')
cleaned_df['legality_standard'] = cleaned_df['legalities'].str.get('standard')
cleaned_df['price_usd'] = cleaned_df['prices'].str.get('usd').astype(float)
# use 'normal' and 'art_crop' images for now
cleaned_df['image_uri_normal'] = cleaned_df['image_uris'].str.get('normal')
cleaned_df['image_uri_art_crop'] = cleaned_df['image_uris'].str.get('art_crop')

# check if any of these columns have null values
print("Count of null values in columns: ")
cleaned_df[['legality_commander', 'legality_standard', 'price_usd', 'image_uri_normal', 'image_uri_art_crop']].isnull().sum()

Count of null values in columns:

legality_commander       0
legality_standard        0
price_usd             5659
image_uri_normal         0
image_uri_art_crop       0
dtype: int64

In [10]:
# for cards missing USD price, try filling in with EUR price at 1 EUR = 1.20 USD conversion rate
cleaned_df['price_usd'] = cleaned_df['price_usd'].fillna(cleaned_df['prices'].str.get('eur').astype(float) * 1.2)

print("Number of cards with missing price (after EUR fill): ", cleaned_df['price_usd'].isnull().sum())
# drop rows with missing price
cleaned_df.dropna(subset=['price_usd'], inplace=True)

Number of cards with missing price (after EUR fill):  5467

In [11]:
# drop legalities, image_uris, and prices columns
final_df = cleaned_df.drop(columns=['legalities', 'image_uris', 'prices'])

### Save final DF to CSV file

In [12]:
final_df.head()

,id,oracle_id,name,set_id,set,set_name,artist_ids,artist,released_at,type_line,...,power,toughness,edhrec_rank,type,subtype,legality_commander,legality_standard,price_usd,image_uri_normal,image_uri_art_crop
0,0000419b-0bba-4488-8f7a-6194544ce91e,b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6,Forest,a2f58272-bba6-439d-871e-7a46686ac018,blb,Bloomburrow,[22ab27e3-6476-48f1-a9f7-9a9e86339030],David Robert Hovey,2024-08-02,Basic Land — Forest,...,NaN,NaN,NaN,Basic Land,Forest,legal,legal,0.25,https://cards.scryfall.io/normal/front/0/0/000...,https://cards.scryfall.io/art_crop/front/0/0/0...
1,0000579f-7b35-4ed3-b44c-db2a538066fe,44623693-51d6-49ad-8cd7-140505caf02f,Fury Sliver,c1d109bc-ffd8-428f-8d7d-3f8d7e648046,tsp,Time Spiral,[d48dd097-720d-476a-8722-6a02854ae28b],Paolo Parente,2006-10-06,Creature — Sliver,...,3,3,9808.0,Creature,Sliver,legal,not_legal,0.46,https://cards.scryfall.io/normal/front/0/0/000...,https://cards.scryfall.io/art_crop/front/0/0/0...
2,00006596-1166-4a79-8443-ca9f82e6db4e,8ae3562f-28b7-4462-96ed-be0cf7052ccc,Kor Outfitter,eb16a2bd-a218-4e4e-8339-4aa1afc0c8d2,zen,Zendikar,[aa7e89ed-d294-4633-9057-ce04dacfcfa4],Kieran Yanner,2009-10-02,Creature — Kor Soldier,...,2,2,19672.0,Creature,Kor Soldier,legal,not_legal,0.11,https://cards.scryfall.io/normal/front/0/0/000...,https://cards.scryfall.io/art_crop/front/0/0/0...
3,0000cd57-91fe-411f-b798-646e965eec37,9f0d82ae-38bf-45d8-8cda-982b6ead1d72,Siren Lookout,fe0dad85-54bc-4151-9200-d68da84dd0f2,xln,Ixalan,[a8e7b854-b15a-421a-b66d-6e68187ae285],Chris Rallis,2017-09-29,Creature — Siren Pirate,...,1,2,18843.0,Creature,Siren Pirate,legal,not_legal,0.04,https://cards.scryfall.io/normal/front/0/0/000...,https://cards.scryfall.io/art_crop/front/0/0/0...
5,0001f1ef-b957-4a55-b47f-14839cdbab6f,ef027846-be81-4959-a6b5-56bd01b1e68a,Venerable Knight,a90a7b2f-9dd8-4fc7-9f7d-8ea2797ec782,eld,Throne of Eldraine,[9c201dbe-db56-429a-87e6-189ea70c2632],Colin Boyer,2019-10-04,Creature — Human Knight,...,2,1,18404.0,Creature,Human Knight,legal,not_legal,0.15,https://cards.scryfall.io/normal/front/0/0/000...,https://cards.scryfall.io/art_crop/front/0/0/0...

In [13]:
print("Number of rows in final DF: ", len(final_df))
print("Count of null values in each column: ")
final_df.isnull().sum()

Number of rows in final DF:  41580
Count of null values in each column:

id                        0
oracle_id                 0
name                      0
set_id                    0
set                       0
set_name                  0
artist_ids                2
artist                    0
released_at               0
type_line                 0
keywords                  0
rarity                    0
color_identity            0
cmc                       0
power                 20914
toughness             20914
edhrec_rank            3654
type                      0
subtype               15322
legality_commander        0
legality_standard         0
price_usd                 0
image_uri_normal          0
image_uri_art_crop        0
dtype: int64

In [14]:
artists = final_df['artist'].value_counts()
print("Top artists: ")
print(artists)

Top artists:
artist
Kev Walker            450
Svetlin Velinov       359
Greg Staples          326
John Avon             317
Dan Murayama Scott    302
                     ...
Mike Zeck               1
Matthew Gregory         1
Theodoru                1
Damian Tedrow           1
Guga Baraldi            1
Name: count, Length: 2098, dtype: int64

In [15]:
sets = final_df['set_name'].value_counts()
print("Top sets: ")
print(sets)

Top sets:
set_name
Secret Lair Drop                                1406
Commander Legends: Battle for Baldur's Gate      440
Innistrad: Double Feature                        433
The Lord of the Rings: Tales of Middle-earth     418
Kamigawa: Neon Dynasty                           383
                                                ...
Dragon's Maze Tokens                               1
Fate Reforged Promos                               1
Tempest Promos                                     1
Planechase Promos                                  1
Battle for Zendikar Promos                         1
Name: count, Length: 487, dtype: int64

In [16]:
final_df.to_csv("./data/final-scryfall-unique-artwork.csv", index=False)